<?php
/**
 * Created by PhpStorm.
 * User: zzyo
 * Date: 2017/2/22
 * Time: 14:02
 */
class TestUser extends \Illuminate\Database\Eloquent\Model {

        protected $table = 'users';



/*    protected function getDateFormat()
    {
        //return parent::getDateFormat(); // TODO: Change the autogenerated stub
        return time();
    }

    protected function asDateTime($value)
    {
        //return parent::asDateTime($value); // TODO: Change the autogenerated stub
        return $value;
    }*/

}